### ISSUE TITLE
초기설정

### ISSUE THREAD

**Issue by lipnus** [lipnus/hackpretty#3]
*BaseApplication : 앱 전체에서 전역적으로 사용될 것들을 처리.

*BaseActivity : 모든 액티비티는 이 액티비티를 상속. 여기에 적용하면 모든 액티비티에 적용.

*Volley : 네트워크 라이브러리. post를 보내고 callback을 받음. (클래스로 제작해놓음)

*Glide: 그래픽 라이브러리. 웹에 있는 그림을 쉽게 이미지뷰에 출력. (그래픽 편집 라이브러리도 추가해놓음)

**Comment by haeungun** [comment]
해결완료
